### ISSUE TITLE
Conflict symfony/config with latest contao/news-bundles

### ISSUE THREAD

**Issue by gian-almada** [hofff/contao-navigation-article#1]
I cant use this package because there is version conflict with contao/news-bundle for symfony/config
can i have option to use oldest version of hoff/contao-navigation (1.9.4)
<img width="445" alt="Screenshot 2024-05-08 at 08 34 45" src="https://github.com/hofff/contao-navigation-article/assets/42395245/2d74f264-51c3-44ab-879c-22897b7b9849">

**Comment by dmolineus** [comment]
Fixed with b2a3dc3dca775a86140367a9acdc637eba7312e7
